version: '3.2'

services:
    db:
        build: ./db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: my_app
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: dev
    apl:
        build: ./apl
        restart: unless-stopped
        volumes:
            - ./sam-app:/go/sam-app
        working_dir: /go/sam-app

